"""Generate the item tables for both the renderer and the Rust backend.

Two sources, both current with the season:

  tools/data/helper/items.json  — datamined identities, rarities and grades
                                  (hero-siege-helper.vercel.app, see fetch_items.py)
  translationsItem.csv          — the game's own display names, keyed by the
                                  same tkey, read straight from the install

Item identity is (type, gameId, weaponType), the triple the packets carry.
Names never come from seeds; a named item's grade never comes from a packet —
the drop that lands on the ground does not state one.
"""

import json
import os
import re
from pathlib import Path

DATA = Path(__file__).parent / "data" / "helper" / "items.json"
GAME = Path(os.environ.get("HERO_SIEGE_BIN", r"F:\Games\Steam\steamapps\common\HeroSiege\bin"))
OUT = Path(__file__).parent.parent / "src" / "items.js"
OUT_RS = Path(__file__).parent.parent / "src-tauri" / "src" / "items.rs"

# the five the tracker announces; the game's "Satanic Set" is the Set rarity
RARITIES = {"Satanic": "Satanic", "Satanic Set": "Set", "Heroic": "Heroic", "Angelic": "Angelic", "Unholy": "Unholy"}
TIERS = {"D": 1, "C": 2, "B": 3, "A": 4, "S": 5, "SS": 6}


def game_names() -> dict[str, str]:
    """tkey -> English name, as the game itself shows it."""
    path = GAME / "translationsItem.csv"
    if not path.exists():
        print(f"note: {path} not found — falling back to the datamined names")
        return {}
    names = {}
    for line in path.read_text(encoding="utf-8-sig", errors="replace").splitlines():
        key, _, rest = line.partition("|")
        key = key.strip()
        if key and not key.startswith("[") and rest:
            name = rest.split("|")[0].strip()
            if name:
                names[key] = name
    return names


translations = game_names()
items, rarities, tiers, drops, zones, places, chases = {}, {}, {}, {}, {}, {}, {}

for entry in json.loads(DATA.read_text(encoding="utf-8")):
    meta = entry.get("metadata") or {}
    identity = meta.get("ID")
    name = translations.get(meta.get("tkey"), meta.get("name") or "").strip()
    if not name or name == "Unknown Name":
        continue
    if isinstance(identity, list) and len(identity) == 3:
        game_id, weapon_type, item_type = identity
        if item_type >= 0:
            items.setdefault(f"{item_type}:{game_id}:{weapon_type}", name)
    rarity = RARITIES.get(meta.get("rarity"))
    if rarity:
        rarities.setdefault(name.lower(), rarity)
    tier = TIERS.get(meta.get("tier"))
    if tier:
        tiers.setdefault(name.lower(), tier)
    # "one in N" — the bigger the number, the rarer the drop
    rate = (entry.get("droprate") or {}).get("base")
    if rarity and isinstance(rate, (int, float)) and rate > 0:
        drops.setdefault(name.lower(), int(rate))
    # where it is tied to: "8-2" is act 8 zone 2, "-D" a dungeon, "-BD" a boss
    # dungeon. Being tied is not exclusivity — the item drops anywhere, just
    # several times more often there, which is the "chase" rate the game shows
    # in green on the tooltip.
    codes = sorted({c for d in (meta.get("drop") or []) for c in (d.get("locations") or [])})
    if rarity and codes:
        zones.setdefault(name.lower(), codes)
        best = [d["chase"] for d in (meta.get("drop") or []) if isinstance(d.get("chase"), (int, float)) and d["chase"] > 0]
        if best:
            chases.setdefault(name.lower(), int(min(best)))
    where = entry.get("dropPlaces")
    where = [where] if isinstance(where, str) else (where or [])
    if rarity and where:
        places.setdefault(name.lower(), sorted({str(w) for w in where}))

header = """// Generated by tools/gen_items.py — do not edit by hand.
// Identities, rarities and grades: datamined tables from hero-siege-helper.
// Display names: the game's own translationsItem.csv."""

out = rf"""{header}
// Item identity is (type, gameId, weaponType); key "type:id:wt".

export const ITEMS = {json.dumps(items, ensure_ascii=False, separators=(",", ":"))};

export const RARITY_BY_NAME = {json.dumps(rarities, ensure_ascii=False, separators=(",", ":"))};

export const TIER_BY_NAME = {json.dumps(tiers, ensure_ascii=False, separators=(",", ":"))};

// how rare a named item is: "one in N", so a bigger number is a rarer drop
export const DROP_RATE = {json.dumps(drops, ensure_ascii=False, separators=(",", ":"))};

// items tied to a place: "8-2" = act 8 zone 2, "8-D" a dungeon, "8-BD" a boss
// dungeon. Being tied is not exclusivity — the item drops anywhere, only more
// often here.
export const DROP_ZONES = {json.dumps(zones, ensure_ascii=False, separators=(",", ":"))};

// the better "one in N" that applies inside those places — the number the
// game's own tooltip prints in green
export const DROP_CHASE = {json.dumps(chases, ensure_ascii=False, separators=(",", ":"))};

// the same in words, for bosses and chests that have no zone code
export const DROP_PLACES = {json.dumps(places, ensure_ascii=False, separators=(",", ":"))};

/// "Act_08_02" is what the game calls the room; the tables call it "8-2".
export function zoneCode(room) {{
  const m = /^Act_(\d+)_(\d+)/i.exec(String(room ?? ''));
  return m ? `${{Number(m[1])}}-${{Number(m[2])}}` : null;
}}

export function zoneLabel(room) {{
  const text = String(room ?? '');
  if (/^Town/i.test(text)) return 'town';
  const m = /^Act_(\d+)_(\d+)/i.exec(text);
  return m ? `Act ${{Number(m[1])}} · Zone ${{Number(m[2])}}` : text.replace(/_/g, ' ');
}}

export const TYPE_NAMES = {{
  0: 'Helmet', 1: 'Chest', 2: 'Boots', 3: 'Weapon', 4: 'Gloves', 5: 'Amulet',
  6: 'Shield', 7: 'Ring', 8: 'Belt', 10: 'Charm', 11: 'Consumable', 12: 'Key',
  13: 'Collectible', 14: 'Material', 15: 'Socketable', 16: 'Relic', 18: 'Vial',
  19: 'Essence Vault',
}};

export const WEAPON_NAMES = {{
  1: 'Sword', 2: 'Dagger', 3: 'Mace', 4: 'Axe', 5: 'Claw', 6: 'Polearm',
  7: 'Chainsaw', 8: 'Staff', 9: 'Cane', 10: 'Wand', 11: 'Book', 12: 'Spellblade',
  13: 'Bow', 14: 'Gun', 15: 'Flask', 16: 'Throwing', 17: 'Novelty',
}};

export function itemName(type, id, weaponType) {{
  return ITEMS[`${{type}}:${{id}}:${{weaponType}}`] ?? ITEMS[`${{type}}:${{id}}:0`] ?? null;
}}

export function typeLabel(type, weaponType) {{
  if (type === 3 && weaponType > 0) return WEAPON_NAMES[weaponType] ?? `Weapon ${{weaponType}}`;
  return TYPE_NAMES[type] ?? `Type ${{type}}`;
}}

// the game grades items D..SS
export const TIER_LETTERS = ['D', 'C', 'B', 'A', 'S', 'SS'];

export function tierLabel(tier) {{
  return TIER_LETTERS[tier - 1] ?? (tier > 0 ? `T${{tier}}` : '');
}}

export function rarityByName(name) {{
  return RARITY_BY_NAME[String(name).toLowerCase().trim()] ?? null;
}}

export function tierByName(name) {{
  return TIER_BY_NAME[String(name).toLowerCase().trim()] ?? 0;
}}
"""

OUT.write_text(out, encoding="utf-8", newline="\n")


def rs_key(key: str) -> int:
    item_type, game_id, weapon_type = (int(part) for part in key.split(":"))
    return (item_type << 24) | (game_id << 8) | weapon_type


def rs_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


rs_items = sorted((rs_key(k), v) for k, v in items.items())
rs_rarities = sorted(rarities.items())
rs_tiers = sorted(tiers.items())

rs_lines = [
    header.replace("//", "//", 1),
    "// Item identity is (type, id, weaponType), packed as (type << 24) | (id << 8) | wt.",
    "",
    f"static ITEMS: [(u32, &str); {len(rs_items)}] = [",
]
rs_lines += [f"    ({k}, {rs_str(v)})," for k, v in rs_items]
rs_lines += ["];", "", f"static RARITY_BY_NAME: [(&str, &str); {len(rs_rarities)}] = ["]
rs_lines += [f"    ({rs_str(k)}, {rs_str(v)})," for k, v in rs_rarities]
rs_lines += ["];", "", f"static TIER_BY_NAME: [(&str, u8); {len(rs_tiers)}] = ["]
rs_lines += [f"    ({rs_str(k)}, {v})," for k, v in rs_tiers]
rs_lines += [
    "];",
    "",
    "/// Item name by identity; falls back to the weapon-type-agnostic key.",
    "pub fn item_name(item_type: i64, id: i64, weapon_type: i64) -> Option<&'static str> {",
    "    lookup(item_type, id, weapon_type).or_else(|| lookup(item_type, id, 0))",
    "}",
    "",
    "fn lookup(item_type: i64, id: i64, weapon_type: i64) -> Option<&'static str> {",
    "    if !(0..256).contains(&item_type) || !(0..65536).contains(&id) || !(0..256).contains(&weapon_type) {",
    "        return None;",
    "    }",
    "    let key = ((item_type as u32) << 24) | ((id as u32) << 8) | weapon_type as u32;",
    "    ITEMS.binary_search_by_key(&key, |(k, _)| *k).ok().map(|i| ITEMS[i].1)",
    "}",
    "",
    "/// Rarity of a named item; names are matched lowercased.",
    "pub fn rarity_by_name(name: &str) -> Option<&'static str> {",
    "    let key = name.trim().to_lowercase();",
    "    RARITY_BY_NAME",
    "        .binary_search_by_key(&key.as_str(), |(k, _)| *k)",
    "        .ok()",
    "        .map(|i| RARITY_BY_NAME[i].1)",
    "}",
    "",
    "/// Grade (1 = D .. 6 = SS) of a named item. The grade is fixed per item,",
    "/// and the packet announcing a drop never states it.",
    "pub fn tier_by_name(name: &str) -> i64 {",
    "    let key = name.trim().to_lowercase();",
    "    TIER_BY_NAME",
    "        .binary_search_by_key(&key.as_str(), |(k, _)| *k)",
    "        .ok()",
    "        .map_or(0, |i| TIER_BY_NAME[i].1 as i64)",
    "}",
    "",
]
OUT_RS.write_text("\n".join(rs_lines), encoding="utf-8", newline="\n")

print(
    f"items: {len(items)}, rarities: {len(rarities)}, grades: {len(tiers)}, "
    f"drop rates: {len(drops)}, zones: {len(zones)}, chase rates: {len(chases)} -> {OUT.name}, {OUT_RS.name}"
)
